/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'courses' : null } |
  { 'hackathons' : null } |
  { 'internships' : null } |
  { 'general' : null };
export interface ChatMessage {
  'authorName' : string,
  'collegeYear' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface CollegeConnect {
  'id' : bigint,
  'tip' : string,
  'collegeName' : string,
  'createdAt' : bigint,
  'year' : string,
}
export interface DMMessage {
  'recipient' : string,
  'sender' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface FeedbackEntry {
  'authorName' : string,
  'collegeYear' : string,
  'feedback' : string,
  'timestamp' : bigint,
}
export interface Post {
  'id' : bigint,
  'upvotes' : bigint,
  'content' : string,
  'createdAt' : bigint,
  'authorYear' : string,
  'connectCount' : bigint,
  'category' : Category,
}
export interface PostStats {
  'categoryCounts' : Array<[Category, bigint]>,
  'topUpvotedPosts' : Array<Post>,
  'topConnectedPosts' : Array<Post>,
  'totalPosts' : bigint,
}
export interface StudentProfile {
  'availableForDM' : boolean,
  'collegeName' : string,
  'name' : string,
  'collegeYear' : string,
}
export interface UserProfile {
  'collegeName' : string,
  'name' : string,
  'collegeYear' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToWishlist' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateStudentProfile' : ActorMethod<
    [string, string, string, boolean],
    undefined
  >,
  'createPost' : ActorMethod<[string, string, Category], bigint>,
  'getAllCollegeConnects' : ActorMethod<[], Array<CollegeConnect>>,
  'getAllFeedbackEntries' : ActorMethod<[], Array<FeedbackEntry>>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAvailableStudents' : ActorMethod<[], Array<StudentProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversation' : ActorMethod<[string, string], Array<DMMessage>>,
  'getLatestChatMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getPostsByCategory' : ActorMethod<[Category], Array<Post>>,
  'getStats' : ActorMethod<[], PostStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[string], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStudentAvailableForDM' : ActorMethod<[string], boolean>,
  'postChatMessage' : ActorMethod<[string, string, string], undefined>,
  'removeFromWishlist' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendDM' : ActorMethod<[string, string, string], undefined>,
  'submitCollegeConnect' : ActorMethod<[string, string, string], bigint>,
  'submitFeedback' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];