/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Variant({
  'courses' : IDL.Null,
  'hackathons' : IDL.Null,
  'internships' : IDL.Null,
  'general' : IDL.Null,
});
export const CollegeConnect = IDL.Record({
  'id' : IDL.Nat,
  'tip' : IDL.Text,
  'collegeName' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorYear' : IDL.Text,
  'connectCount' : IDL.Nat,
  'category' : Category,
});
export const PostStats = IDL.Record({
  'categoryCounts' : IDL.Vec(IDL.Tuple(Category, IDL.Nat)),
  'topUpvotedPosts' : IDL.Vec(Post),
  'topConnectedPosts' : IDL.Vec(Post),
  'totalPosts' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addToWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
  'getAllCollegeConnects' : IDL.Func([], [IDL.Vec(CollegeConnect)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
  'getStats' : IDL.Func([], [PostStats], ['query']),
  'getWishlist' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'submitCollegeConnect' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Variant({
    'courses' : IDL.Null,
    'hackathons' : IDL.Null,
    'internships' : IDL.Null,
    'general' : IDL.Null,
  });
  const CollegeConnect = IDL.Record({
    'id' : IDL.Nat,
    'tip' : IDL.Text,
    'collegeName' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorYear' : IDL.Text,
    'connectCount' : IDL.Nat,
    'category' : Category,
  });
  const PostStats = IDL.Record({
    'categoryCounts' : IDL.Vec(IDL.Tuple(Category, IDL.Nat)),
    'topUpvotedPosts' : IDL.Vec(Post),
    'topConnectedPosts' : IDL.Vec(Post),
    'totalPosts' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addToWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
    'getAllCollegeConnects' : IDL.Func(
        [],
        [IDL.Vec(CollegeConnect)],
        ['query'],
      ),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
    'getStats' : IDL.Func([], [PostStats], ['query']),
    'getWishlist' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'submitCollegeConnect' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };