/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'courses' : IDL.Null,
  'hackathons' : IDL.Null,
  'internships' : IDL.Null,
  'general' : IDL.Null,
});
export const CollegeConnect = IDL.Record({
  'id' : IDL.Nat,
  'tip' : IDL.Text,
  'collegeName' : IDL.Text,
  'createdAt' : IDL.Int,
  'year' : IDL.Text,
});
export const FeedbackEntry = IDL.Record({
  'authorName' : IDL.Text,
  'collegeYear' : IDL.Text,
  'feedback' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'upvotes' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
  'authorYear' : IDL.Text,
  'connectCount' : IDL.Nat,
  'category' : Category,
});
export const StudentProfile = IDL.Record({
  'availableForDM' : IDL.Bool,
  'collegeName' : IDL.Text,
  'name' : IDL.Text,
  'collegeYear' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'collegeName' : IDL.Text,
  'name' : IDL.Text,
  'collegeYear' : IDL.Text,
});
export const DMMessage = IDL.Record({
  'recipient' : IDL.Text,
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ChatMessage = IDL.Record({
  'authorName' : IDL.Text,
  'collegeYear' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PostStats = IDL.Record({
  'categoryCounts' : IDL.Vec(IDL.Tuple(Category, IDL.Nat)),
  'topUpvotedPosts' : IDL.Vec(Post),
  'topConnectedPosts' : IDL.Vec(Post),
  'totalPosts' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateStudentProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
  'getAllCollegeConnects' : IDL.Func([], [IDL.Vec(CollegeConnect)], ['query']),
  'getAllFeedbackEntries' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAvailableStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(DMMessage)],
      ['query'],
    ),
  'getLatestChatMessages' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ChatMessage)],
      ['query'],
    ),
  'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
  'getStats' : IDL.Func([], [PostStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStudentAvailableForDM' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'postChatMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendDM' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitCollegeConnect' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'courses' : IDL.Null,
    'hackathons' : IDL.Null,
    'internships' : IDL.Null,
    'general' : IDL.Null,
  });
  const CollegeConnect = IDL.Record({
    'id' : IDL.Nat,
    'tip' : IDL.Text,
    'collegeName' : IDL.Text,
    'createdAt' : IDL.Int,
    'year' : IDL.Text,
  });
  const FeedbackEntry = IDL.Record({
    'authorName' : IDL.Text,
    'collegeYear' : IDL.Text,
    'feedback' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'upvotes' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
    'authorYear' : IDL.Text,
    'connectCount' : IDL.Nat,
    'category' : Category,
  });
  const StudentProfile = IDL.Record({
    'availableForDM' : IDL.Bool,
    'collegeName' : IDL.Text,
    'name' : IDL.Text,
    'collegeYear' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'collegeName' : IDL.Text,
    'name' : IDL.Text,
    'collegeYear' : IDL.Text,
  });
  const DMMessage = IDL.Record({
    'recipient' : IDL.Text,
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ChatMessage = IDL.Record({
    'authorName' : IDL.Text,
    'collegeYear' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PostStats = IDL.Record({
    'categoryCounts' : IDL.Vec(IDL.Tuple(Category, IDL.Nat)),
    'topUpvotedPosts' : IDL.Vec(Post),
    'topConnectedPosts' : IDL.Vec(Post),
    'totalPosts' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateStudentProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
    'getAllCollegeConnects' : IDL.Func(
        [],
        [IDL.Vec(CollegeConnect)],
        ['query'],
      ),
    'getAllFeedbackEntries' : IDL.Func([], [IDL.Vec(FeedbackEntry)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAvailableStudents' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(DMMessage)],
        ['query'],
      ),
    'getLatestChatMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getPostsByCategory' : IDL.Func([Category], [IDL.Vec(Post)], ['query']),
    'getStats' : IDL.Func([], [PostStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStudentAvailableForDM' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'postChatMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendDM' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitCollegeConnect' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };